In [1]:
import numpy as np

In [2]:
print(np.__version__) # show the numpy version

1.20.3


In [18]:
myarr=np.array([3,54,2,11,231111],np.int32) #np.intx basically says that, x bits numbers are allowed.
myarr

array([     3,     54,      2,     11, 231111])

In [28]:
myarr=np.array([[3,54,2,11,231111],[3,54,2,11,44]])
print(myarr[0,4]) #accessing the element by 2D index
print("\n")
myarr[0]

231111




array([     3,     54,      2,     11, 231111])

In [36]:
print(myarr.shape) # it is a 2 by 5 array 2D array

print(myarr.dtype)

print(type(myarr))

(2, 5)
int32
<class 'numpy.ndarray'>


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim) # will print the number of dimension of this array. it is 3.

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [41]:
print(arr[0,1,2]) # will give 6 as output
arr[0,1,2]=23
print(arr[0,1,2]) 

6
23


# Conversion from other data structures to numpy (Dictionary) 

In [50]:
dict = {"a": 1, "b": 2, "c": 3, "d": 4}
data = list(dict.values())

# Try with dict.keys() as well as dict.items()

an_array = np. array(data)
print(an_array)
print(an_array.dtype)

[1 2 3 4]
int32


# Functions : Zeroes,ones,lspace,empty and arange

In [61]:
zeroes=np.zeros((2,5,3))

print(zeroes.shape)
print(zeroes.dtype)
zeroes[0,4,1]=34
print(zeroes)

(2, 5, 3)
float64
[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0. 34.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [62]:
rnd=np.arange(15) # range of entries inside array from 0 to 14 inclusive
print(rnd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [63]:
lspace=np.linspace(1,50,10) # gives us 10 elements with equal spaing between them.
print(lspace)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [65]:
randomarray = np.empty((3,5))
print(randomarray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
idm=np.identity(4) # will give an identity matrix of size 4 by 4
print(idm)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Reshape 

In [68]:
x=np.arange(99)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [69]:
x.reshape(3,3,11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
