In [1]:
import numpy as np

In [2]:
print(np.__version__) # show the numpy version

1.20.3


In [18]:
myarr=np.array([3,54,2,11,231111],np.int32) #np.intx basically says that, x bits numbers are allowed.
myarr

array([     3,     54,      2,     11, 231111])

In [28]:
myarr=np.array([[3,54,2,11,231111],[3,54,2,11,44]])
print(myarr[0,4]) #accessing the element by 2D index
print("\n")
myarr[0]

231111




array([     3,     54,      2,     11, 231111])

In [36]:
print(myarr.shape) # it is a 2 by 5 array 2D array

print(myarr.dtype)

print(type(myarr))

(2, 5)
int32
<class 'numpy.ndarray'>


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim) # will print the number of dimension of this array. it is 3.

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
